# Generated by Django 2.2 on 2023-01-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profileimage',
            field=models.ImageField(blank=True, upload_to='assets'),
        ),
    ]
