# Generated by Django 2.2 on 2023-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
