# Generated by Django 2.2 on 2023-01-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20230107_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
    ]
