# Generated by Django 2.2 on 2023-01-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='level',
            new_name='PastQuestion',
        ),
    ]
