# Generated by Django 2.2 on 2023-01-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_auto_20230105_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(upload_to='assets')),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=200, null=True)),
                ('File', models.FileField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.department'),
        ),
        migrations.AlterField(
            model_name='material',
            name='File',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.department'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='File',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Textbooks',
        ),
        migrations.AddField(
            model_name='textbook',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.department'),
        ),
    ]
