# Generated by Django 2.2 on 2023-01-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_auto_20230106_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastquestion',
            old_name='Title',
            new_name='course',
        ),
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
