# Generated by Django 2.2 on 2023-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_auto_20230106_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_Message', models.CharField(max_length=300, null=True)),
                ('Name', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=200, null=True)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
